### ISSUE TITLE
AttributeError: object has no attribute 'updated_at'

### ISSUE THREAD

**Issue by unixfox** [SamuelMoraesF/CachetNotifier#1]
I'm unable to get working CachetNotifier with Twitter, I'm getting this error:

```
2016-10-06 19:09:04,561 - apscheduler.executors.default - INFO - Running job "check (trigger: interval[0:00:05], next run at: 2016-10-06 19:09:09 CEST)" (scheduled at 2016-10-06 19:09:04.559939+02:00)
2016-10-06 19:09:04,713 - apscheduler.executors.default - ERROR - Job "check (trigger: interval[0:00:05], next run at: 2016-10-06 19:09:09 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/share/cachetnotif/bot.py", line 171, in check
    itemhash = hashlib.md5(item.title + item.updated_at).hexdigest()
  File "/usr/local/lib/python2.7/dist-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'updated_at'
```

With my little knowledge with python, I tried to remove `item.updated_at` from [bot.py](https://github.com/SamuelMoraesF/CachetNotifier/blob/master/bot.py) but it gives me an almost same error:

```
2016-10-06 20:21:59,927 - apscheduler.executors.default - INFO - Running job "check (trigger: interval[0:00:30], next run at: 2016-10-06 20:22:29 CEST)" (scheduled at 2016-10-06 20:21:59.926678+02:00)
2016-10-06 20:22:00,041 - apscheduler.executors.default - ERROR - Job "check (trigger: interval[0:00:30], next run at: 2016-10-06 20:22:29 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/share/cachetnotif/bot.py", line 175, in check
    newitem(item.title, itemhash, item.message, item.status)
  File "/usr/local/lib/python2.7/dist-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'message'
```

I don't really know why it isn't working, here is my configuration file (`bot.cfg`):

```
# Cachet Notifications System
# Current supports XMPP, Twitter and Pushover

[cachet]

# Url of Cachet RSS
url: https://status.aresrpg.fr/rss

# Cache file to write notified items
cache: tmp/notified.cache

# Interval of checks (in seconds)
interval: 30

[logs]

# If false logs will saved in file, else, to stdout
stdout: true

# File to save logs
filename: log/bot.log

# LogLevel - CRITICAL, ERROR, WARNING, INFO and DEBUG
level: DEBUG



[xmpp]

# Enable or disable XMPP notifications
xmpp: false

# JID of the receiver separated by comma
to: receiver1@xmppserver.com,receiver2@xmppserver.com

# JID of the user that will send the message
user: sender@xmppserver.com

# ... and the password
password: password666



[pushover]

# Enable or disable pushover notifications
pushover: false

# Pushover App Token
token: 111111111111111111111111111111

# Pushover Users/Groups key separated by comma
user: 1111111111111111111111111111,2222222222222222222222222222

# Pushover priority - https://pushover.net/api#priority
priority: 1

# Pushover notification sound - https://pushover.net/api#sounds
sound: siren



[twitter]

# Enable or disable twitter notifications
twitter: true

# Twitter Consumer Key (API Key)
app_key: xxxxxxxxxxxxxxxxxxxxxxxxxxx

# Twitter Consumer Secret (API Secret)
app_secret: xxxxxxxxxxxxxxxxxxxxxx

# Twitter OAuth Access Token
oauth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxx

# Twitter OAuth Access Token Secret
oauth_token_secret: xxxxxxxxxxxxxxxxxxxxxx

# Content to insert after the issue, at the end ot the tweet
after: #AresRPGStatus



[irc]

# Enable or Disable IRC
irc: false

# IRC Server to connect
server: irc.example.org

# Port of the IRC server
port: 6667

# Nick to be used to notify
nick: cachetnotify

# Nicks and Channels to receive notifications, separated by comma
receivers: nick1,nick2,#channel1,#channel2

# Enable or disable SSL
ssl: true
```

**Comment by bleuchtang** [comment]
I had the same problem, It looks like RSS feeds missing 'updated_at' information. My solution is to use Cachet API instead of RSS. My modifications are available here: 
https://github.com/bleuchtang/CachetNotifier/commit/60988333b57713edc7dc5539952461dcf1c03c3b
